# Generated by Django 5.0.7 on 2025-01-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='falls_id',
            field=models.TextField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
