# Generated by Django 5.0.7 on 2025-02-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_remove_chapter_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='falls_id',
            field=models.TextField(),
        ),
    ]
