# Generated by Django 5.0.7 on 2025-02-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0005_webbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webbook',
            name='img',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='webbook',
            name='url',
            field=models.URLField(),
        ),
    ]
