# Generated by Django 5.0.7 on 2025-02-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0006_alter_webbook_img_alter_webbook_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webbook',
            name='img',
        ),
    ]
