# Generated by Django 5.0.7 on 2025-02-28 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0007_remove_webbook_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='parsing.webbook'),
            preserve_default=False,
        ),
    ]
